# Apply these read-only caches to the junction projects as well as local ones.
artifacts:
  servers:
  - url: https://gbm.gnome.org:11003
    push: false
  - url: https://cache.projectbluefin.io:11001
    push: false

source-caches:
  servers:
  - url: https://gbm.gnome.org:11003
    push: false
  - url: https://cache.projectbluefin.io:11001
    push: false
