name: personal-os
min-version: 2.6
element-path: elements

(@):
- gnome.bst:freedesktop-sdk.bst:include/runtime.yml
- include/image.yml

options:
  arch:
    type: arch
    description: Target architecture
    variable: arch
    values: [x86_64]

sandbox:
  build-arch: '%{arch}'

aliases:
  gnome: https://gitlab.gnome.org/GNOME/
  github: https://github.com/
  pypi: https://files.pythonhosted.org/packages/
  docker: https://download.docker.com/linux/static/stable/x86_64/

plugins:
- origin: junction
  junction: plugins/buildstream-plugins.bst
  sources: [patch]
- origin: junction
  junction: plugins/buildstream-plugins-community.bst
  sources: [git_repo]
- origin: junction
  junction: gnome.bst
  elements: [collect_initial_scripts]

fatal-warnings:
- overlaps
- unaliased-url
- unstaged-files
