name: Validate OS

on:
  pull_request:
    paths:
      - .github/workflows/validate.yml
      - buildstream.conf
      - project.conf
      - elements/**
      - files/**
      - include/**
      - patches/**
      - scripts/bst

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Prepare BuildStream
        run: |
          sudo modprobe fuse
          podman pull "$(cat include/builder-image.txt)"

      - name: Validate project
        run: ./scripts/bst show --deps all --format '%{name}' oci/image.bst > /dev/null
